version: '3.8'

services:
  mongo:
    image: mongo
    container_name: Event-Source-CQRS-Example-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  redis:
    container_name: Event-Source-CQRS-Example-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mysqlsrv:
    container_name: Event-Source-CQRS-Example-MySQL
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - mysqldbdata:/data/db
    networks:
      - mysql-compose-network

  adminer:
    container_name: Event-Source-CQRS-Example-MySQL-Adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

volumes:
  mongodbdata:
  mysqldbdata:
  redis:
    driver: local
